os: linux

dist: bionic

language: generic

env:
  - COQ_INSTALL_COMMAND='sudo add-apt-repository -y ppa:jgross-h/many-coq-versions && sudo apt-get update && sudo apt-get install coq-8.6.1' LEGACY_COQ_VERSION=1 
  - COQ_INSTALL_COMMAND='sudo add-apt-repository -y ppa:jgross-h/many-coq-versions && sudo apt-get update && sudo apt-get install coq-8.7.2' LEGACY_COQ_VERSION=1 
  - COQ_INSTALL_COMMAND='sudo add-apt-repository -y ppa:jgross-h/many-coq-versions && sudo apt-get update && sudo apt-get install coq-8.8.2' LEGACY_COQ_VERSION=1 
  - COQ_INSTALL_COMMAND='conda install -c conda-forge coq=8.9.1' LEGACY_COQ_VERSION=0
  - COQ_INSTALL_COMMAND='conda install -c conda-forge coq=8.10.1' LEGACY_COQ_VERSION=0
  - COQ_INSTALL_COMMAND='conda install -c conda-forge coq=8.11.2' LEGACY_COQ_VERSION=0
  - COQ_INSTALL_COMMAND='conda install -c conda-forge coq=8.12.2' LEGACY_COQ_VERSION=0

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=3.9
  - conda activate test-environment
  - eval "$COQ_INSTALL_COMMAND"

script:
  - python --version
  - pip --version
  - coqtop --version
  
  - python setup.py sdist bdist_wheel
  - pip install --user --upgrade --force-reinstall dist/coq_jupyter-*.tar.gz 'jupyter_client<=6.1.12' 'jupyter_kernel_test<=0.3'
  - python -m coq_jupyter.install
  - python test/kernel_test.py -v
