name: CI Tests

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1' # At 12:00 on Monday.

jobs:
  package:
    uses: ./.github/workflows/package.yml

  test-docker:
    name: Test against Coq release (Docker)
    needs: package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        coq-version:
          - "8.6"
          - "8.7"
          - "8.8"
          - "8.13"
          - "8.14"
          - "8.15"
          - "8.16"
          - "8.17"
          - "8.18"
          - "latest"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: packages
          path: dist

      - uses: addnab/docker-run-action@v3
        with:
          image: coqorg/coq:${{ matrix.coq-version }}
          options: -v ${{ github.workspace }}:/github/workspace
          run: /github/workspace/test/container_test_entrypoint.sh

